const server_url = "http://localhost:4000/api";
const SIGNUP = "SIGNUP";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const MENU_OPEN = "MENU_OPEN";
const MENU_CLOSE = "MENU_CLOSE";
const HOME_MOUNTED = "HOME_MOUNTED";
const HOME_UNMOUNTED = "HOME_UNMOUNTED";
const IS_LOADING = "IS_LOADING";
const ISNT_LOADING = "ISNT_LOADING";
const SAVE_ALL_ITEMS = "SAVE_ALL_ITEMS";
const SET_SEARCHING = "SET_SEARCHING";
const SET_SEARCHED_ITEMS = "SET_SEARCHED_ITEMS";

export {
  server_url,
  SIGNUP,
  LOGIN,
  LOGOUT,
  MENU_OPEN,
  MENU_CLOSE,
  HOME_MOUNTED,
  HOME_UNMOUNTED,
  IS_LOADING,
  ISNT_LOADING,
  SAVE_ALL_ITEMS,
  SET_SEARCHING,
  SET_SEARCHED_ITEMS,
};
